### ISSUE TITLE
Unable to log in on student page

### ISSUE THREAD

**Issue by SwatiBang** [manitagahlayan/Jobs4U#1]
Error while logging into student page.
Steps:
1. Select 'I am a student'.
2. On Student login page, provide username and password.
3. Click on a login button and it throws an error on profile view.

PFA screenshot of the error.
![screen shot 2016-08-24 at 3 10 27 pm](https://cloud.githubusercontent.com/assets/19677279/17951489/44dd4ee4-6a17-11e6-8d88-18deb35d865a.png)

**Comment by pallaviborde** [comment]
Kindly update database according to following steps,
1. DROP TABLE IF EXISTS `Student`;
2. CREATE TABLE `Student` (
   
   `email` varchar(50) NOT NULL,
   
   `password` varchar(20) NOT NULL,
   
   `firstName` varchar(50),
   
   `lastName` varchar(50),
   
   `telephone` varchar(20),
   
   `address` varchar(100),
   
   `summary` LONGTEXT,
   
   `expectedJob` varchar(100),
   
   `skills` LONGTEXT,
   
   `schoolName` varchar(100),
   
   `schoolStartMonth` varchar(10),
   
   `schoolStartYear` varchar(10),
   
   `schoolEndMonth` varchar(10),
   
   `schoolEndYear` varchar(10),
   
   `schoolDegree` varchar(100),
   
   `schoolMajor` varchar(100),
   
   `workCompanyName` varchar(100),
   
   `workJobTitle` varchar(100),
   
   `workStartMonth` varchar(10),
   
   `workStartYear` varchar(10),
   
   `workEndMonth` varchar(10),
   
   `workEndYear` varchar(10),
   
   `workJobResponsibility` LONGTEXT,
   
   `projectName` varchar(100),
   
   `projectDescription` LONGTEXT,
   
   PRIMARY KEY (`email`)

) ENGINE=InnoDB AUTO_INCREMENT=7;
1. alter table Student
   add column isTempFlag varchar(10),
   add column job1 int(10),
   add column job2 int(10),
   add column job3 int(10),
   add column job4 int(10),
   add column job5 int(10);
2. alter table student
   add column preferedInTime varchar(10),
   add column preferedOutTime varchar(10);

**Comment by SwatiBang** [comment]
Working fine. Closing defect.
