### ISSUE TITLE
Graduate date is inappropriate

### ISSUE THREAD

**Issue by SwatiBang** [manitagahlayan/Jobs4U#3]
On student's detail page, Graduate date (estimate if attending) is not showing dates greater than 2016.

![screen shot 2016-08-26 at 3 58 20 pm](https://cloud.githubusercontent.com/assets/19677279/18022707/f3373042-6ba5-11e6-9a83-1470a3bb6357.png)

Regards,
Swati Bang

**Comment by manitagahlayan** [comment]
Fixed. Please verify. Thanks!

**Comment by SwatiBang** [comment]
Working fine. Hence, closing the defect.
